version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  sqs:
    image: vsouza/sqs-local
    ports:
      - "9324:9324"

  celery-worker:
    image: andreyst/celery-sandbox
    volumes:
      - ./:/files
    working_dir: /files
    command: celery -A celery_sandbox worker --loglevel INFO
    depends_on:
      - rabbitmq
      - redis
      - sqs

  flower:
    image: andreyst/celery-sandbox
    volumes:
      - ./:/files
    ports:
      - "5555:5555"
    working_dir: /files
    command: celery flower -A celery_sandbox --address=0.0.0.0 --port=5555 --broker="amqp://rabbitmq:5672"
